version: "3"
services:
    node-app:
        build: 
            context: .
            args:
                NODE_ENV: production
        ports: 
            - "5000:3000"
        env_file: 
            - ./config/config.env
        command: node server.js